#define Nseat 10
#define Ntel 8
#define NzoneA 5
#define NzoneB 10
#define NzoneC 10
#define Ncash 4
#define PzoneA 0.2
#define PzoneB 0.4
#define PzoneC 0.4
#define CzoneA 30
#define CzoneB 25
#define CzoneC 20
#define Tcashlow 2
#define Tcashhigh 4
#define Nseatlow 1
#define Nseathigh 5
#define Tseatlow 5
#define Tseathigh 10
#define Pcardsucces 90